title: Haoge Zhou
description: Electrical Engineer 
author: Haoge Zhou
avatar: /profile.png
email: hgzhoucn@gmail.com
location: Riverside, CA 92507


paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
Linkedin:
  username: Haoge Zhou
  card: summary
logo: profile.png
social:
  name: Haoge Zhou
  links:
    - https://github.com/HaogeZhou
    - https://www.linkedin.com/in/haoge-zhou/
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
